### ISSUE TITLE
Mouse over empty account graph causes page to turn completely white

### ISSUE THREAD

**Issue by returntoreality** [SFTtech/abrechnung#107]
Error in web console (twice):
TypeError: n is null
    content BalanceHistoryGraph.tsx:36
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    Xt React
react-dom.production.min.js:216:199

**Comment by mikonse** [comment]
should be fixed in the latest release 0.9.0
