### ISSUE TITLE
Docker image without building

### ISSUE THREAD

**Issue by ovizii** [SFTtech/abrechnung#123]
Hi there,

this looks very promising, do you intend to release a ready-made docker image on some registry by any chance?

**Comment by mikonse** [comment]
Just added automatic docker image builds and added a section to the documentation:

Check it out and give us a short notice if this works for you:
https://abrechnung.readthedocs.io/en/latest/usage/installation.html#docker-compose

**Comment by ovizii** [comment]
Thanks for the reply. I tried those instructions and got some build errors but lets ignore that, I am sure I could have them solved by checking the other issues here or googling.

I just wanted to mention that this was not what I was asking about as it still is no pre-built docker image I can just pull from a registry. Not sure if that is not possible with this project or its too early to ask about? Anyway, here are my thoughts: 
- I still have to clone a repository and make sure to keep it updated
- I can't properly modify the docker-compose file without making a copy
- I need the Dockerfile and other stuff too
- I am still apparently building the image

Other projects I am self-hosting for my own usage are more self-sustained: I either define a .env or just download their docker-compose.yml file, adapt it and start it up and the image gets pulled from the docker hub. An update is as simple as pulling the new image from the registry.

**Comment by mikonse** [comment]
In #125  I think I've added what you initially meant.

Prebuilt docker images are now available on [quay.io](https://quay.io/organization/abrechnung) and I've adapted the `docker-compose.prod.yaml`  to reference the prebuilt images. Currently as I've written in the docs you would still clone the repo to get the docker-compose file and the .env template. You could obviously simply copy the docker-compose from the github repo itself as an alternative.

I've just realized that there are still some issues with the docker-compose which should be fixed on the latest commit to master.
