### ISSUE TITLE
Web Cache not working correctly

### ISSUE THREAD

**Issue by leofah** [SFTtech/abrechnung#129]
In our group at some point we had a desynchronization of available data. Some people did not see all transactions, others could not see the correct group accounts, deleted accounts were visible, new accounts were missing. After clearing the Web Cache everything showed up correctly.

Maybe an automatic cache refresh can be implemented to update the cache every few days or so to mitigate the problem.

**Comment by mikonse** [comment]
most of the cache related issues should be fixed with the latest release v0.10.0
