### ISSUE TITLE
Search Field of Users in transaction edit screen vanishes.

### ISSUE THREAD

**Issue by leofah** [SFTtech/abrechnung#171]
If you search for a user to participate in a transaction this field hides if the list is short enough, that no scrollbar is needed. Saving the transaction in this state keeps the search result in the transaction overview.
The field and missing users are only shown if the site is reloaded.

Tested in:
- firefox 118.0.1 (64-bit)
- chromium 117.0.5938.132

**Comment by mikonse** [comment]
Seems to be fixed in recent versions
