### ISSUE TITLE
"user is not a member of this group" error when uploading image to unsaved transaction

### ISSUE THREAD

**Issue by Raupinger** [SFTtech/abrechnung#175]
afaict this happens because unsaved transactions get a negative id which wont be found in [transaction.py:61](https://github.com/SFTtech/abrechnung/blob/4377815c2a89d78e334271fac6ae1a62fd128443/abrechnung/application/transactions.py#L61), which results in the misleading error

**Comment by mikonse** [comment]
fixed by #178
