### ISSUE TITLE
Purchase position view seems to be broken 

### ISSUE THREAD

**Issue by maciejewiczow** [SFTtech/abrechnung#209]
![2024-02-17_17h03_08](https://github.com/SFTtech/abrechnung/assets/37718435/5d6bc446-1dd7-4da5-9cf4-eef904f89673)
As can be seen in the animation above, the checkboxes do not work 
Idk what system info to give. There are no errors in the browser console, nor does the network tab look anything out of the ordinary. I am using a docker setup with a local database on a local server.

**Comment by maciejewiczow** [comment]
After tinkering a bit a got it to update and actually save the positions from database, by first entering the amount/clicking one of the checkboxes, and then adding a new row with any amount other than 0 or with any of the checkboxes checked

**Comment by mikonse** [comment]
Interesting, thanks a lot for the report!

Currently the position table is a bit fiddly unfortunately, I agree. I'll have to revisit this and try to polish it a bit once I get around to it.

Which version are you running currently? Latest release?

**Comment by TheJJ** [comment]
Can confirm the bug on our running ssn instance, also happens on mobile.

**Comment by maciejewiczow** [comment]
Idk how to check the exact version being run, but I am using the `latest-release` tag from the docker repo. The images have been pulled around a week ago

**Comment by mikonse** [comment]
If added a fix in the latest release (v0.13.3) which fixes an issue that occurs when copying positions. This might have been the reason for the issue you were seeing. Can you check whether it still occurs?

**Comment by maciejewiczow** [comment]
Sorry for late reply. Just pulled the latest docker images, sadly the issue persists

**Comment by maciejewiczow** [comment]
The issue also still seems to be present on the demo instance as well

**Comment by TheJJ** [comment]
After some investigation I can say the bug is still present on current master (d26106d4d97b101f5fbad03fe41e9f23015d4683).

It does not occur in the nx development mode (`npx nx serve`) but after building the webapp with `npx nx build web` application. I suspect a "compiler bug".

**Comment by TheJJ** [comment]
as @mikonse suspected correctly, removing `StrictMode` lets the bug appear in development mode :)

**Comment by mikonse** [comment]
this has been fixed by #222
