### ISSUE TITLE
Docker doesnt start on raspberry pi

### ISSUE THREAD

**Issue by OWL4C** [SFTtech/abrechnung#210]
`sudo docker-compose -f docker-compose.prod.yaml up
Starting abrechnung_api_1 ... done
Creating abrechnung_cron_1   ... error
Creating abrechnung_mailer_1 ... 

Creating abrechnung_mailer_1 ... error

ERROR: for abrechnung_mailer_1  Cannot create container for service mailer: bad parameter: link is not supported

ERROR: for cron  Cannot create container for service cron: bad parameter: link is not supported

ERROR: for mailer  Cannot create container for service mailer: bad parameter: link is not supported

ERROR: for frontend  Container "2c0b30dba0f6" is unhealthy.
ERROR: Encountered errors while bringing up the project.`

My .env 
`ABRECHNUNG_SERVICE__URL=http://localhost:8080
ABRECHNUNG_SERVICE__API_URL=https://localhost:8080/api
ABRECHNUNG_SERVICE__NAME=Abrechnung
ABRECHNUNG_DATABASE__HOST=abrechnung_postgres
ABRECHNUNG_DATABASE__USER=abrechnung
ABRECHNUNG_DATABASE__DBNAME=abrechnung
ABRECHNUNG_DATABASE__PASSWORD=#1

ABRECHNUNG_API__SECRET_KEY=#4
ABRECHNUNG_API__PORT=8080
ABRECHNUNG_API__ID=default

ABRECHNUNG_REGISTRATION__ENABLED=false

ABRECHNUNG_EMAIL__ADDRESS=#2
ABRECHNUNG_EMAIL__HOST=imap.gmail.com
ABRECHNUNG_EMAIL__PORT=993
ABRECHNUNG_EMAIL__MODE=smtp-ssl
#ABRECHNUNG_EMAIL__MODE=smtp-starttls # use this in production, remove line above
ABRECHNUNG_EMAIL__AUTH__USERNAME=#2
ABRECHNUNG_EMAIL__AUTH__PASSWORD=#3

POSTGRES_USER=abrechnung
POSTGRES_PASSWORD=#1
POSTGRES_DATABASE=abrechnung
`

with the current docker-compose.prod.yaml

**Comment by mikonse** [comment]
Can you try the latest `docker-compose.prod.yaml` from the master branch? I've removed the `link` settings in #212 which could fix your issue.
