### ISSUE TITLE
image compression broken since refactor 

### ISSUE THREAD

**Issue by Raupinger** [SFTtech/abrechnung#216]
I recently updated my main abrechnung instance and have been unable to upload images since. Seems reproducible on https://demo.abrechnung.sft.lol as well.

**How to reproduce:**
- create event and add an image bigger than 1mb 
- try to save

**expected behaviour:**
image gets compressed to just under 1mb 
**actual behaviour:**
image is slightly to big and server returns 413 Request Entity Too Large

It seems like the code for the upload dialog has been refactored since I contributed the initial implementation of the compression feature. Just looking at the changes on GitHub, I don't immediately see how the actual compression part would have changed though.

**Comment by Raupinger** [comment]
I plan on looking into this myself eventually, but since i cant downgrade to an old fronted with my up-to-date server anymore i need set up a dev server first before i can bisect this and i dont know when I'll find time for that. Just wanted to open an issue first in case someone else runs into this.

**Comment by mikonse** [comment]
Hi, 
thanks for the report!
Always happy to accept PRs if you get around to it.

**Comment by mikonse** [comment]
I think that this was never an issue with the implementation of the image compression but a misconfiguration in the nginx of the demo instance.

I've adjusted the configuration and now everything seems to work as expected.
