### ISSUE TITLE
Unable to start service

### ISSUE THREAD

**Issue by chiel1112** [SFTtech/abrechnung#220]
![image](https://github.com/user-attachments/assets/ad7a708c-766d-4ed9-a66e-e319e1e9e281)
I cannot get the service to start unfortunately, i am using Ubuntu via WSL2.

**Comment by mikonse** [comment]
Could you provide a bit more detail

From a first glance it looks like you have a syntax error in your yaml config file

**Comment by chiel1112** [comment]
Thank you for the quick reply! I have my yaml file below with the passwords etc crossed out
![image](https://github.com/user-attachments/assets/4cc0a699-3aac-4f06-a4cf-54bdf1b71992)

**Comment by chiel1112** [comment]
as for more detail, this happens when i run abrechnung demo, abrechnung admin, and any other command other than --help

**Comment by mikonse** [comment]
It looks like the indent of the email config block is a bit odd

**Comment by chiel1112** [comment]
It is the same as the default file!![image](https://github.com/user-attachments/assets/cac22875-773a-4c57-980f-25d13f70b0ae)

**Comment by TheJJ** [comment]
did you use tabs? they may look the same optically but the yaml parser seems unhappy. try using spaces, or enable whitespace highlighting in your editor so you can spot the error. (this has nothing to do with Abrechnung, its just a yaml parsing error apparently)

**Comment by chiel1112** [comment]
retyping everything by hand has indeed worked, thank you for the help!
