### ISSUE TITLE
Failed to create database pool

### ISSUE THREAD

**Issue by chiel1112** [SFTtech/abrechnung#225]
![image](https://github.com/user-attachments/assets/5bca50f3-3286-4451-a562-8bf86f16ded1)
So, while I am sure that I am just missing something, I can't seem to find what I am missing here to create this error. All I can find is that it has something to do with wrong DNS when googling this issue? However my postgresql and abrechnung config just point towards localhost...

**Comment by chiel1112** [comment]
here is my related abrechnung.yaml config:
![image](https://github.com/user-attachments/assets/c86d1a8f-9eeb-4b31-8908-d8eaa667f36c)
and here is my postgresql config:
![image](https://github.com/user-attachments/assets/4e984ce5-4ca9-46eb-a0aa-62c63592e761)

**Comment by mikonse** [comment]
The host key in the database section should not contain the port of the database server, there's a separate key in the config to configure the port.

```yaml
database:
  host: localhost
  user: ...
  password: ...
  dbname: ...
  port: 5433
```

**Comment by chiel1112** [comment]
if i try that it still tries to connect to 5432...
![image](https://github.com/user-attachments/assets/ab230312-e262-4d93-8470-1773b87a9eea)
![image](https://github.com/user-attachments/assets/016c7f47-11ee-4a27-a5be-c943e218cb0c)

**Comment by chiel1112** [comment]
in the end i realised that i currently have nothing else running on 5432 anyway so now db migrate does work

However, I still cannot create an user, as it gives this error...
![image](https://github.com/user-attachments/assets/8315c8b1-1a9a-4af1-8a8b-86cb3238831f)

**Comment by chiel1112** [comment]
okay, it did work, but now I can't figure out how to start abrechnung itself...
(I did receive an email confirming my account creation, when i executed abrechnung mailer) but cant seem to figure out how to start the web server

**Comment by TheJJ** [comment]
you need to build the webapp with `npx nx build` in the frontend directory to get the production build which you then serve with any webserver, e.g. nginx.
 `npx nx serve` to get the development build.

**Comment by chiel1112** [comment]
and just to confirm, running `abrechnung api` should just start up the api right, and then the frontend should work?

**Comment by chiel1112** [comment]
Because right now when i moved the files (that include the index.html file) to /var/www/html i just get this so i presume my api isn't started? 
![image](https://github.com/user-attachments/assets/982e9bbd-81a1-4325-b9c5-e3556d722e3b)

**Comment by TheJJ** [comment]
yes, the api needs to be running as it is contacted by the website/app.
you have to provide a `config.json` in your web root, you can copy and edit it from the example config (currently in `frontend/apps/web/src/assets/config.json`
