### ISSUE TITLE
allow users to invite others in cases with disabled / restricted registration

### ISSUE THREAD

**Issue by mikonse** [SFTtech/abrechnung#63]
If I am hosting an Abrechnung instance with restricted or disabled registration I still want to be able to invite my friends to join.

Options:
- enable "verified" users to generate invite links with which other can register themselves

**Comment by mic-e** [comment]
The group invite tokens could double as tokens for registration.

Users that join with such a token will receive a lower-permission account which will not be able to create new groups or invite users to existing groups.

**Comment by mikonse** [comment]
implemented by #79
